zergcalls_homepage:
    pattern:  /
    defaults: { _controller: ZergCallsBundle:Calls:index }

zergcalls_sites:
    pattern:  /sites
    defaults: { _controller: ZergCallsBundle:Calls:listSites }
  
zergcall_addsite:
    pattern:  /sites/add
    defaults: { _controller: ZergCallsBundle:Calls:addSite }
    
zergcall_modifysite:
    pattern:  /sites/modify/{id}
    defaults: { _controller: ZergCallsBundle:Calls:modifySite }
    
zergcall_delsite:
    pattern:  /sites/del/{id}
    defaults: { _controller: ZergCallsBundle:Calls:delSite }
    
zergcalls_contacts:
    pattern:  /contacts
    defaults: { _controller: ZergCallsBundle:Calls:listContacts }
  
zergcall_addcontact:
    pattern:  /contacts/add
    defaults: { _controller: ZergCallsBundle:Calls:addContact }
    
zergcall_modifycontact:
    pattern:  /contacts/modify/{id}
    defaults: { _controller: ZergCallsBundle:Calls:modifyContact }
    
zergcall_delcontact:
    pattern:  /contacts/del/{id}
    defaults: { _controller: ZergCallsBundle:Calls:delContact }
    
zergcalls_calls:
    pattern:  /calls
    defaults: { _controller: ZergCallsBundle:Calls:listCalls }
  
zergcall_addcall:
    pattern:  /calls/add
    defaults: { _controller: ZergCallsBundle:Calls:addCall }
    
zergcall_modifycall:
    pattern:  /calls/modify/{id}
    defaults: { _controller: ZergCallsBundle:Calls:modifyCall }
    
zergcall_delcall:
    pattern:  /calls/del/{id}
    defaults: { _controller: ZergCallsBundle:Calls:delCall }
    
zergcalls_licences:
    pattern:  /licences
    defaults: { _controller: ZergCallsBundle:Calls:listLicences }
  
zergcall_addlicence:
    pattern:  /licences/add
    defaults: { _controller: ZergCallsBundle:Calls:addLicence }
    
zergcall_modifylicence:
    pattern:  /licences/modify/{id}
    defaults: { _controller: ZergCallsBundle:Calls:modifyLicence }
    
zergcall_dellicence:
    pattern:  /licences/del/{id}
    defaults: { _controller: ZergCallsBundle:Calls:delLicence }