zergcalls_accueil:
    pattern:  /{page}
    defaults: { _controller: ZergCallsBundle:Calls:index , page: 1 }
    requirements:
        page: \d*
zergcalls_voir:
    pattern:  /article/{id}
    defaults: { _controller: ZergCallsBundle:Calls:voir }

zerg_calls_voir_slug:
    pattern:  /{annee}/{slug}.{format}
    defaults: {_controller: ZergCallsBundle:Calls:voirSlug , _format: html}
    requirements:
        annee:  \d{4}
        format: html|xml
        
zergcalls_ajouter:
    pattern:  /ajouter
    defaults: { _controller: ZergCallsBundle:Calls:ajouter }
    
zergcalls_modifier:
    pattern:  /modifier/{id}
    defaults: { _controller: ZergCallsBundle:Calls:modifier }
    requirements:
        id: \d+
        
zergcalls_supprimer:
    pattern:  /supprimer/{id}
    defaults: { _controller: ZergCallsBundle:Calls:supprimer }
    requirements:
        id: \d+