HelloTheWorld:
    pattern:  /hello-world
    defaults: { _controller: ZergCallsBundle:Calls:index }
    
ByeByeTheWorld:
    pattern:  /byebye-world
    defaults: { _controller: ZergCallsBundle:Calls:bye }
